export const RANDOM_DRINK_LIST_REQUEST = 'RANDOM_DRINK_LIST_REQUEST'
export const RANDOM_DRINK_LIST_FAIL = 'RANDOM_DRINK_LIST_FAIL'
export const RANDOM_DRINK_LIST_SUCCESS = 'RANDOM_DRINK_LIST_SUCCESS'

export const POPULAR_DRINK_LIST_REQUEST = 'POPULAR_DRINK_LIST_REQUEST'
export const POPULAR_DRINK_LIST_FAIL = 'POPULAR_DRINK_LIST_FAIL'
export const POPULAR_DRINK_LIST_SUCCESS = 'POPULAR_DRINK_LIST_SUCCESS'

export const LATEST_DRINK_LIST_REQUEST = 'LATEST_DRINK_LIST_REQUEST'
export const LATEST_DRINK_LIST_FAIL = 'LATEST_DRINK_LIST_FAIL'
export const LATEST_DRINK_LIST_SUCCESS = 'LATEST_DRINK_LIST_SUCCESS'
