export const INGREDIENT_DETAILS_REQUEST = 'INGREDIENT_DETAILS_REQUEST'
export const INGREDIENT_DETAILS_FAIL = 'INGREDIENT_DETAILS_FAIL'
export const INGREDIENT_DETAILS_SUCCESS = 'INGREDIENT_DETAILS_SUCCESS'

export const RANDOM_DRINK_LIST_REQUEST = 'RANDOM_DRINK_LIST_REQUEST'
export const RANDOM_DRINK_LIST_FAIL = 'RANDOM_DRINK_LIST_FAIL'
export const RANDOM_DRINK_LIST_SUCCESS = 'RANDOM_DRINK_LIST_SUCCESS'

export const POPULAR_DRINK_LIST_REQUEST = 'POPULAR_DRINK_LIST_REQUEST'
export const POPULAR_DRINK_LIST_FAIL = 'POPULAR_DRINK_LIST_FAIL'
export const POPULAR_DRINK_LIST_SUCCESS = 'POPULAR_DRINK_LIST_SUCCESS'

export const LATEST_DRINK_LIST_REQUEST = 'LATEST_DRINK_LIST_REQUEST'
export const LATEST_DRINK_LIST_FAIL = 'LATEST_DRINK_LIST_FAIL'
export const LATEST_DRINK_LIST_SUCCESS = 'LATEST_DRINK_LIST_SUCCESS'

export const SEARCH_DRINKS_REQUEST = 'SEARCH_DRINKS_REQUEST'
export const SEARCH_DRINKS_FAIL = 'SEARCH_DRINKS_FAIL'
export const SEARCH_DRINKS_SUCCESS = 'SEARCH_DRINKS_SUCCESS'
