export const RANDOM_INGREDIENT_LIST_REQUEST = 'RANDOM_INGREDIENT_LIST_REQUEST'
export const RANDOM_INGREDIENT_LIST_FAIL = 'RANDOM_INGREDIENT_LIST_FAIL'
export const RANDOM_INGREDIENT_LIST_SUCCESS = 'RANDOM_INGREDIENT_LIST_SUCCESS'

export const POPULAR_INGREDIENT_LIST_REQUEST = 'POPULAR_INGREDIENT_LIST_REQUEST'
export const POPULAR_INGREDIENT_LIST_FAIL = 'POPULAR_INGREDIENT_LIST_FAIL'
export const POPULAR_INGREDIENT_LIST_SUCCESS = 'POPULAR_INGREDIENT_LIST_SUCCESS'

export const INGREDIENT_LIST_REQUEST = 'INGREDIENT_LIST_REQUEST'
export const INGREDIENT_LIST_FAIL = 'INGREDIENT_LIST_FAIL'
export const INGREDIENT_LIST_SUCCESS = 'INGREDIENT_LIST_SUCCESS'

export const INGREDIENT_DETAILS_REQUEST = 'INGREDIENT_DETAILS_REQUEST'
export const INGREDIENT_DETAILS_FAIL = 'INGREDIENT_DETAILS_FAIL'
export const INGREDIENT_DETAILS_SUCCESS = 'INGREDIENT_DETAILS_SUCCESS'
